### ISSUE TITLE
Retry handling can lead to duplicated artifact uploads, which fails `actions/deploy-pages`

### ISSUE THREAD

**Issue by Bo98** [actions/upload-pages-artifact#97]
If the upload fails due to a timeout in the "finalizing artifact upload" stage, the uploader retries and uploads the artifact again. However, the server has actually received all the data if it has reached the "finalizing" stage so it's possible that the timeout is simply in receiving the confirmation from the server.

Take the following example output:

```
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Beginning upload of artifact content to blob storage
Uploaded bytes 8388608
Uploaded bytes 16777216
Uploaded bytes 25165824
Uploaded bytes 33554432
Uploaded bytes 41943040
Uploaded bytes 50331648
Uploaded bytes 52845291
Finished uploading artifact content to blob storage!
SHA256 hash of uploaded artifact zip is 581e085d8ee66e610a32e88c1e0e70205caaf6c4082dc4c23ccdd678e9def1cc
Finalizing artifact upload
Attempt 1 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/FinalizeArtifact. Retrying request in 3000 ms...
Artifact github-pages.zip successfully finalized. Artifact ID 1271248021
Artifact github-pages has been successfully uploaded! Final size is 52845291 bytes. Artifact ID is 1271248021
```

The end result was two artifacts with the same name:

![image](https://github.com/actions/upload-pages-artifact/assets/1190754/902956ff-15ac-4f69-b95c-2b6e1e933648)

This fails `actions/deploy-pages`:

```
Fetching artifact metadata for "github-pages" in this workflow run
Found 2 artifact(s)
Error: Fetching artifact metadata failed. Is githubstatus.com reporting issues with API requests, Pages, or Actions? Please re-run the deployment at a later time.
Error: Error: Multiple artifacts named "github-pages" were unexpectedly found for this workflow run. Artifact count is 2.
    at getArtifactMetadata (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:89:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:66:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)
Error: Error: Multiple artifacts named "github-pages" were unexpectedly found for this workflow run. Artifact count is 2.
```

The retry handling should be more intelligent in its stages and only retry the finalizing stage if that stage fails. If it continues to fail (assuming that can happen), it should probably abort entirely or find a better way to delete the current artifact before retrying the entire upload.

---

An alternative workaround could be to make `actions/deploy-pages` accept an `artifact_id` rather than only accept `artifact_name`. It doesn't really solve the core issue, but is something I would be comfortable making a PR for if deemed nice to have.

**Comment by jcreedcmu** [comment]
Fwiw, I see this is also being tracked on `upload-artifact`: https://github.com/actions/upload-artifact/issues/531

**Comment by mauritz-lovgren** [comment]
As a workaround, we use the geekyeggo/delete-artifact@v5 action to remove the GitHub-pages artifact just before deployment (and just after for cleanup).

**Comment by boharad786** [comment]
jobs:%0A%20%20%23%20Build%20job%0A%20%20build:%0A%20%20%20%20%23%20%3CNot%20provided%20for%20brevity%3E%0A%20%20%20%20%23%20At%20a%20minimum%20this%20job%20should%20upload%20artifacts%20using%20actions/upload-pages-artifact%0A%0A%20%20%23%20Deploy%20job%0A%20%20deploy:%0A%20%20%20%20%23%20Add%20a%20dependency%20to%20the%20build%20job%0A%20%20%20%20needs:%20build%0A%0A%20%20%20%20%23%20Grant%20GITHUB_TOKEN%20the%20permissions%20required%20to%20make%20a%20Pages%20deployment%0A%20%20%20%20permissions:%0A%20%20%20%20%20%20pages:%20write%20%20%20%20%20%20%23%20to%20deploy%20to%20Pages%0A%20%20%20%20%20%20id-token:%20write%20%20%20%23%20to%20verify%20the%20deployment%20originates%20from%20an%20appropriate%20source%0A%0A%20%20%20%20%23%20Deploy%20to%20the%20github-pages%20environment%0A%20%20%20%20environment:%0A%20%20%20%20%20%20name:%20github-pages%0A%20%20%20%20%20%20url:%20$%7B%7B%20steps.deployment.outputs.page_url%20%7D%7D%0A%0A%20%20%20%20%23%20Specify%20runner%20+%20deployment%20step%0A%20%20%20%20runs-on:%20ubuntu-latest%0A%20%20%20%20steps:%0A%20%20%20%20%20%20-%20name:%20Deploy%20to%20GitHub%20Pages%0A%20%20%20%20%20%20%20%20id:%20deployment%0A%20%20%20%20%20%20%20%20uses:%20actions/deploy-pages@v4%20%23%20or%20specific%20%22vX.X.X%22%20version%20tag%20for%20this%20action
